### PR TITLE
Add 10 additional icon styles.

### PR DESCRIPTION
**Pull request by nullKomplex**
Adds Glowing Icons, Gear Set Icons, and all FC emblem icon colors as options for icon styles.

I'm quite an amateur and this likely won't be up to par with your standards so no hard feelings if you decline this.

### CODE REVIEW

**Comment by lichie567** [comment]
Hey, thanks for contributing. This and your other PR look fine to me, but could you re-open them to target the develop branch? I just added that branch late last night and it might not have existed yet when you opened these PRs. Sorry!

**Comment by lichie567** [comment]
Hey, I finally got around to previewing these and I don't think I'll be merging this. The 'Glowing' style icons seem to be missing for a few of the jobs, and the FC style icons are smaller textures that don't look very good. I might add the Gearset icons though.

**Comment by nullKomplex** [comment]
Ah rip, glowing was just offset by one and I just noticed and fixed it. I agree with the FC style icons. Locally I have them larger and offset to account for their size but I'm not happy with how hacky it was so I didn't push it.

**Comment by lichie567** [comment]
If you would like to re-open a PR with just the gear set icons and the (fixed) glowing icons, I would probably accept it.

**Pull request closed without merging**
